x-app: &app
  image: gn-head
  build: .
  environment: &env
    RAILS_ENV: ${RAILS_ENV:-development}
    RAILS_DB_HOST: postgres
    SOLID_QUEUE_IN_PUMA: true

  volumes: &volumes
    - .:/app
  tmpfs:
    - /tmp
    - /app/tmp/pids

services:
  web:
    <<: *app
    command: bin/rails server -b 0.0.0.0 -p 3000
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true

  postgres:
    image: postgres:17.4-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

volumes:
  postgres:

